name: BendingTournament
version: ${project.version}
main: com.Jacksonnn.BendingTournament.BendingTournament
authors: [Jacksonnn]
api-version: 1.13
commands:
  bendingtournament:
    aliases: [bt, btourney, bendingt, btournament, tourny, tournament]
    usage: /<command>